openapi: 3.1.1
info:
  title: Microblog API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/posts:
    post:
      summary: Create post
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDTO'
  /api/timeline:
    get:
      summary: Get home timeline
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema: {type: integer, default: 0}
        - in: query
          name: size
          schema: {type: integer, default: 20}
      responses:
        '200':
          description: Page of posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/PostDTO'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    NewPost:
      type: object
      properties:
        content: {type: string}
        visibility: {type: string, enum: [PUBLIC, PRIVATE], default: PUBLIC}
      required: [content]
    UserDTO:
      type: object
      properties:
        id: {type: integer}
        login: {type: string}
        displayName: {type: string}
    PostDTO:
      type: object
      properties:
        id: {type: integer}
        author: {$ref: '#/components/schemas/UserDTO'}
        content: {type: string}
        createdAt: {type: string, format: date-time}
        likeCount: {type: integer}
        commentCount: {type: integer}