name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres  
          POSTGRES_USER: 12345
          POSTGRES_PASSWORD: microblog
        ports: ['5432:5432']
      # redis:
      #   image: redis:7
      #   ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build and run unit tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/microblog
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 12345
          # SPRING_REDIS_HOST: localhost
          # SPRING_REDIS_PORT: 6379
        run: mvn -B -DskipTests=false test -e
      - name: Build package
        run: mvn -B -DskipTests package
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
